[package]
name = "carbonyl"
version = "0.0.3"
edition = "2021"

[dependencies]
libc = "0.2"
unicode-width = "0.1.13"
unicode-segmentation = "1.11.0"
chrono = "0.4.38"

[lib]
name = "carbonyl"
path = "src/lib.rs"
crate-type = ["cdylib"]
